// This file has been generated by Specta. Do not edit this file manually.
/**
 *  Display metadata supplied by the frontend provider registry. Availability
 *  policy is evaluated in Rust against the stored provider configuration.
 */
export type AgentProviderDescriptor = {
	id: string,
	name: string,
	requiresApiKey: boolean,
	requiresBaseUrl: boolean,
};

/**
 *  Everything Rust needs to resolve *and* validate an agent's provider for a
 *  run, without owning the settings store itself: the frontend still owns
 *  `settings.ai.providers`/`defaultAgentId` and passes them through as data
 *  on every run. Rust is the one that decides what's usable and, when the
 *  agent's own provider isn't, which fallback to apply and persist — see
 *  `agents::lifecycle::resolve_runnable_agent`.
 */
export type AgentRunConfig = {
	providers: AgentProviderDescriptor[],
	configs: { [key in string]: ProviderConfig },
	defaultAgentId: string | null,
	temperature: number | null,
	maxTokens: number,
};

export type AgentStreamEvent = { type: "user_message_persisted" } | { type: "text_delta"; delta: string; accumulated: string } | { type: "status"; status: string | null } | { type: "assistant_turn_persisted" } | { type: "tool_dispatch"; tool_call_id: string; extension_id: string; tool_id: string; arguments: any } | { type: "tool_dispatch_cancelled"; tool_call_id: string } | { type: "mcp_permission_request"; tool_call_id: string; server_id: string; tool_id: string; agent_id: string } | { type: "mcp_permission_cancelled"; tool_call_id: string } | { type: "error"; message: string } | { type: "completed" } | { type: "cancelled" };

export type AliasConflict = {
	objectId: string,
	itemName: string,
};

export type AliasMatch = {
	objectId: string,
	itemType: string,
	autoExecute: boolean,
};

export type Application = {
	id?: string,
	name: string,
	path: string,
	usageCount?: number,
	icon?: string | null,
	lastUsedAt?: number | null,
	/**
	 *  Platform-native bundle / process identifier when discoverable:
	 *  - macOS: `CFBundleIdentifier` from `Contents/Info.plist` (e.g. `com.apple.Safari`)
	 *  - Linux: `StartupWMClass` from the `.desktop` entry, or the basename of `Exec=`
	 *    as a fallback (e.g. `firefox`)
	 *  - Windows: not extracted — `.lnk` shortcuts don't carry a bundle id
	 * 
	 *  Consumed by `IApplicationService.isRunning()` — extensions should prefer
	 *  this field over `name` when calling `isRunning`, with `name` as a fallback.
	 */
	bundleId?: string | null,
};

// Category of a calculator answer. Drives icon selection in the UI.
export type CalcKind = "math" | "unit" | "currency" | "date" | "time" | "base" | "color" | "percent" | "ratio";

// One calculator answer, ready for display.
export type CalcResult = {
	// Main display value, e.g. `"177.8 cm"`.
	value: string,
	// Supporting line, e.g. the resolved date or the rate used.
	detail: string,
	kind: CalcKind,
};

export type ChatMessage = {
	id: string,
	role: string,
	content: string,
	timestamp: number,
	toolCalls: ToolCall[] | null,
	toolCallId: string | null,
	providerContext: any[] | null,
};

export type ChatParams = {
	modelId: string,
	temperature: number | null,
	maxTokens: number,
	systemPrompt: string | null,
	tools: ToolDefinition[] | null,
};

export type ChatStreamEvent = { type: "token"; token: string } | { type: "status"; status: string } | { type: "toolCall"; id: string; name: string; input: any } | { type: "providerContext"; item: any };

export type ChatStreamEventPayload = { type: "token"; token: string } | { type: "status"; status: string } | { type: "toolCall"; id: string; name: string; input: any } | { type: "providerContext"; item: any } | { type: "done" } | { type: "error"; error: string };

export type Command = {
	id: string,
	name: string,
	extension: string,
	trigger: string,
	type: string,
	usageCount?: number,
	icon: string | null,
	lastUsedAt?: number | null,
	subtitle?: string | null,
	/**
	 *  Right-side row label shown in root search. `None` falls back to the
	 *  owning extension's display name in the frontend mapper.
	 */
	typeLabel?: string | null,
	/**
	 *  `true` when the registration declares an argument schema. Set on the
	 *  dynamic-command path only; manifest commands stay `false` and the
	 *  frontend derives their answer from the loaded manifest instead.
	 */
	hasArguments?: boolean,
	/**
	 *  `true` for runtime-registered commands from
	 *  `commandsService.replaceDynamicCommands(...)`. Manifest-declared
	 *  commands always serialize as `false`. Defaults to `false` so older
	 *  persisted rows decode without migration.
	 */
	isDynamic?: boolean,
};

/**
 *  Represents a search result contributed by a frontend extension.
 *  Sent from TypeScript to Rust for unified ranking.
 */
export type ExternalSearchResult = {
	objectId: string,
	name: string,
	description?: string | null,
	type: string,
	score: number,
	icon?: string | null,
	extensionId?: string | null,
	category?: string | null,
	style?: string | null,
	priority?: ResultPriority | null,
};

// Wire shape for one search hit.
export type FileHit = {
	// 16-char lowercase hex of the stable u64 file id.
	fileId: string,
	name: string,
	path: string,
	type: FileType,
	isDir: boolean,
	// Unix mtime seconds. Widened to i64 on the wire.
	modifiedAt: number,
	score: number,
	pinned: boolean,
	source: HitSource,
};

/**
 *  User-configurable index settings, pushed from TS via
 *  `file_index_set_config` (mirror of the applications scan-paths bridge).
 */
export type FileIndexConfig = {
	enabled: boolean,
	// Absolute paths to index. Empty ⇒ `$HOME`.
	includeRoots: string[],
	// Extra exclude patterns layered on top of the built-in defaults.
	excludePatterns: string[],
	indexHidden: boolean,
};

export type FileSearchResponse = {
	hits: FileHit[],
	/**
	 *  Candidate collection hit the cap — results are best-effort from the
	 *  static-rank-ordered prefix of the arena.
	 */
	truncated: boolean,
	// The whole arena was scanned (i.e. `!truncated`, plus tail).
	scannedAll: boolean,
	indexGeneration: number,
	work: WorkMeter,
};

/**
 *  File classification derived from the extension (dirs use `Folder`).
 *  Stored as one byte in `EntryMeta.ext_class`; the kebab-case string form
 *  is the wire contract with the view's type-filter dropdown.
 */
export type FileType = "document" | "image" | "code" | "audio-video" | "archive" | "folder" | "other";

/**
 *  Where a hit came from: the local index or an on-demand deep-search
 *  provider (mdfind / Everything / plocate).
 */
export type HitSource = "local" | "deep";

// Index lifecycle state, kebab-case on the wire.
export type IndexStateKind = "disabled" | "building" | "ready" | "rescanning" | "cap-reached";

export type IndexStatus = {
	state: IndexStateKind,
	entryCount: number,
	lastScanMs: number,
	snapshotLoaded: boolean,
	capReached: boolean,
};

// A user-defined alias bound to a single search-index item (application or command).
export type ItemAlias = {
	objectId: string,
	alias: string,
	itemName: string,
	itemType: string,
	createdAt: number,
};

/**
 *  Where within the chosen display the launcher sits.
 * 
 *  `Free` is the drag result and stores **fractions of the monitor**, not
 *  pixels. Pixels would put the launcher off-screen the first time a display
 *  is unplugged or a resolution changes, with no way back except a reset;
 *  fractions land in the same relative spot on any display and are clamped
 *  into the work area on every reveal.
 */
export type LauncherAnchor = 
// Horizontally centred; top edge at `bias` of the monitor's height.
{ kind: "topWeighted"; bias: number } | 
// Centred on both axes.
{ kind: "centered" } | 
/**
 *  Free position from a drag, as fractions of the monitor for the
 *  window's top-left corner.
 */
{ kind: "free"; x: number; y: number };

// Which display the launcher opens on.
export type LauncherMonitorChoice = 
/**
 *  The display the mouse pointer is currently on. The default, and what
 *  macOS has always done — Windows and Linux only gained it with this
 *  feature.
 */
"cursor" | 
// Always the primary display, wherever the pointer is.
"primary";

/**
 *  The whole user-facing placement preference. Default reproduces the
 *  pre-#596 behaviour exactly, so an install that never opens the setting
 *  sees no change.
 */
export type LauncherPlacement = {
	monitor: LauncherMonitorChoice,
	anchor: LauncherAnchor,
	/**
	 *  Whether dragging magnetically snaps to the default position. A
	 *  `#[derive(Default)]` would give this `false` (bool's own default) —
	 *  wrong, since snapping ships on. Hence the hand-written impl below.
	 */
	snapEnabled: boolean,
};

export type MergedSearchResponse = {
	results: SearchResult[],
	aliasMatch?: AliasMatch | null,
};

export type ModelInfo = {
	id: string,
	label: string,
	reasoningEfforts: string[] | null,
};

// Which convention a number is written in.
export type NumberFormat = 
// `1,234.56` — point decimal, comma grouping.
"point" | 
// `1.234,56` — comma decimal, point grouping.
"comma";

// A normalized, structured locale representation.
export type ParsedLocale = {
	// 2- or 3-letter ISO 639 language code (always lowercase, e.g. "en", "zh", "de")
	language: string,
	// 4-letter ISO 15924 script subtag (Titlecase, e.g. "Hans", "Hant", "Latn")
	script: string | null,
	// 2-letter ISO 3166-1 country code or 3-digit UN M.49 region code (e.g. "US", "DE", "419")
	region: string | null,
	// Variant subtag if present (e.g. "1901")
	variant: string | null,
	// Original raw tag
	raw: string,
};

export type ProviderConfig = {
	enabled: boolean,
	name: string | null,
	providerType: string | null,
	apiKey: string | null,
	baseUrl: string | null,
	lastModelId: string | null,
	openAIApiMode: string | null,
	hostedWebSearch: boolean | null,
	reasoningEffort: string | null,
	temperature: number | null,
	maxTokens: number | null,
};

/**
 *  A frontend-supplied item to be ranked against a query. The `id` is opaque
 *  to Rust — it is returned verbatim, best-match first, so the caller can map
 *  the ordered ids back to its own item objects.
 */
export type RankInput = {
	id: string,
	title: string,
	subtitle?: string | null,
	keywords?: string[],
};

/**
 *  Result-level priority hint. `Top` pins the result above all tier 1–5
 *  results (synthetic answers like Calculator's expression result).
 */
export type ResultPriority = "top";

export type SearchResult = {
	objectId: string,
	name: string,
	type: string,
	score: number,
	path?: string | null,
	icon?: string | null,
	extensionId?: string | null,
	description?: string | null,
	typeLabel?: string | null,
	hasArguments?: boolean,
	style?: string | null,
	alias?: string | null,
	/**
	 *  Tier ordinal from `ranker::Tier` (0=Pinned .. 5=FrecencyOnly), computed
	 *  by `merged_search`'s classify pass. Lets the frontend consume Rust's
	 *  tier directly instead of re-deriving it with its own approximation.
	 */
	tier: number,
};

export type SearchableItem = { category: "application" } & Application | { category: "command" } & Command;

export type StreamEventPayload = {
	streamId: string,
	event: ChatStreamEventPayload,
};

export type SystemAction = "sleep" | "hibernate" | "lockScreen" | "logOut" | "restart" | "shutDown";

// Per-item tier classification result, returned by `classify_many`.
export type TierResult = {
	id: string,
	tier: number,
};

export type ToolCall = {
	id: string,
	name: string,
	input: any,
};

export type ToolDefinition = {
	name: string,
	description: string,
	parameters: any,
};

// Input for updating a command's runtime metadata (currently: subtitle only).
export type UpdateCommandMetadataInput = {
	commandObjectId: string,
	subtitle: string | null,
};

/**
 *  Per-query work accounting. Surfaced on the wire for the status card's
 *  debug view and asserted on by the perf regression tests — the budget is
 *  enforced as operation counts, not wall-clock, so CI stays deterministic.
 */
export type WorkMeter = {
	bytesScanned: number,
	candidatesCollected: number,
	candidatesScored: number,
	fuzzyChecks: number,
	/**
	 *  True when the query was answered by narrowing the previous query's
	 *  candidate set instead of a fresh arena scan.
	 */
	narrowed: boolean,
};
