import * as fs from 'fs'
import * as path from 'path'
import { execSync } from 'child_process'

/**
 * Symlink-safe path comparison. `path.resolve` does not resolve
 * symlinks; `git rev-parse --show-toplevel` returns the real path.
 * On macOS the tmpdir lives at `/var/folders/...` but realpaths to
 * `/private/var/folders/...`, so a naive string compare would always
 * miss for paths under tmp (and any other symlinked mount).
 */
function realResolve(p: string): string {
  try {
    return fs.realpathSync(p)
  } catch {
    return path.resolve(p)
  }
}

/**
 * True iff `cwd` is itself the top level of a git repo (not a nested
 * directory inside a parent repo). `git rev-parse --show-toplevel`
 * walks UP from cwd to find the enclosing repo's root; if that root
 * isn't cwd, the repo belongs to a parent (e.g. running `asyar publish`
 * from inside the launcher monorepo's `extensions/foo/` directory),
 * and its remote / index / tags MUST NOT be used for this extension.
 *
 * Returns false if cwd is not inside any git repo at all.
 */
export function isOwnGitRoot(cwd: string): boolean {
  try {
    const toplevel = execSync('git rev-parse --show-toplevel', { cwd, stdio: 'pipe' })
      .toString().trim()
    return realResolve(toplevel) === realResolve(cwd)
  } catch {
    return false
  }
}

/**
 * Find the origin URL of the FIRST enclosing parent git repo above
 * `cwd`. If `cwd` is itself a git root, we start walking from its
 * parent directory so the function answers "what monorepo am I nested
 * inside, if any?". Returns null when there is no such parent repo
 * or it has no `origin` remote.
 *
 * Used to detect the parent-repo trap: a stored extension repo URL
 * that equals this value was saved during an old broken publish run
 * (before the isOwnGitRoot guard existed) — it's stale and should be
 * discarded so we auto-create a dedicated repo instead.
 */
export function findEnclosingParentOrigin(cwd: string): string | null {
  let start = realResolve(cwd)
  if (isOwnGitRoot(start)) start = path.dirname(start)
  if (start === path.dirname(start)) return null
  try {
    const toplevel = execSync('git rev-parse --show-toplevel', { cwd: start, stdio: 'pipe' })
      .toString().trim()
    // If the enclosing toplevel turns out to be the same path we just
    // dirnamed out of (because git's realpath traversal climbed back
    // into a repo whose .git is at or below `start`), treat it as no
    // parent — otherwise we'd report the child's own origin.
    if (realResolve(toplevel) === realResolve(cwd)) return null
    return execSync('git remote get-url origin', { cwd: toplevel, stdio: 'pipe' })
      .toString().trim()
      .replace('git@github.com:', 'https://github.com/')
      .replace(/\.git$/, '')
  } catch {
    return null
  }
}

/**
 * Ensure `cwd` has at least one commit. Idempotent: returns silently
 * if HEAD already resolves. Used by the publish auto-create flow so
 * that a half-initialized `.git/` (e.g. left over from an interrupted
 * earlier run that did `git init` but never committed) doesn't break
 * the eventual `git push`.
 */
export function ensureInitialCommit(cwd: string): void {
  try {
    execSync('git log -1', { cwd, stdio: 'pipe' })
    return
  } catch { /* no commits yet — create one */ }
  execSync('git add .', { cwd, stdio: 'pipe' })
  execSync('git commit -m "Initial extension"', { cwd, stdio: 'pipe' })
}

/**
 * Write a sensible .gitignore in `cwd` if one doesn't already exist.
 * Used right before the auto-create flow's initial `git add .` so we
 * don't commit build artifacts or installed deps to the brand-new repo.
 */
export function ensureExtensionGitignore(cwd: string): void {
  const gitignorePath = path.join(cwd, '.gitignore')
  if (fs.existsSync(gitignorePath)) return
  fs.writeFileSync(
    gitignorePath,
    [
      '# Generated by `asyar publish` on first run; safe to extend.',
      'node_modules/',
      'dist/',
      '*.log',
      '.DS_Store',
      '',
    ].join('\n'),
  )
}
