// AUTO-GENERATED by asyar-launcher/scripts/generate-permission-catalog.mjs — do not edit.
// Written together with asyar-launcher's copy by the same generator; run
// `pnpm gen:permission-catalog` (from asyar-launcher) after changing
// asyar-launcher's permissions.rs::get_required_permission.

// Every permission string the launcher's Rust permission gate can require.
// Not the full set of manifest-declarable permissions — see this package's
// VALID_PERMISSIONS in lib/manifest.ts for that (deliberately broader:
// includes declarative-only permissions this gate never checks).
export const GATED_PERMISSIONS = [
  "app:frontmost-watch",
  "application:read",
  "browser:bookmarks.read",
  "browser:history.read",
  "browser:page.read",
  "browser:page.write",
  "browser:tabs.read",
  "browser:tabs.write",
  "cache:read",
  "cache:write",
  "clipboard:read",
  "clipboard:write",
  "entitlements:read",
  "extension:invoke",
  "feedback:announce",
  "files:read",
  "files:search",
  "fs:read",
  "fs:watch",
  "fs:write",
  "network",
  "notes:read",
  "notes:write",
  "notifications:send",
  "oauth:use",
  "power:inhibit",
  "preferences:read",
  "preferences:write",
  "process:kill",
  "process:read",
  "runs:track",
  "screen:pick-color",
  "selection:read",
  "shell:open-url",
  "shell:spawn",
  "snippets:contribute",
  "storage:read",
  "storage:write",
  "systemEvents:read",
  "timers:cancel",
  "timers:list",
  "timers:schedule",
  "tools:register",
  "window:manage"
] as const;
