// AUTO-GENERATED by scripts/generate-known-runtimes.mjs — do not edit.
// Run `npm run gen:known-runtimes` after changing asyar-launcher's
// runtimes/catalog.fallback.json.

// Mirrors asyar-launcher's runtimes::catalog::known_names() (Rust), which
// reads this same catalog.fallback.json — that file is the real source of
// truth for both sides.
export const KNOWN_RUNTIMES = [
  "bun",
  "claude",
  "uv"
] as const;
