// asyar-launcher/src/lib/ipc/privacyCommands.ts
// Tauri command wrappers, re-exported through ./commands (the barrel).
import { invokeSafe } from './invokeSafe';

// ── Clipboard Capture-Time Privacy Filter ─────────────────────────────────────

export type ClipboardPrivacySkipReason =
  | { kind: 'none' }
  | { kind: 'transient' }
  | { kind: 'concealed' }
  | { kind: 'autoGenerated' }
  | { kind: 'optedOutOfHistory' }
  | { kind: 'sourceDenylist'; value: string };

export interface ClipboardPrivacyClassification {
  skip: boolean;
  reason: ClipboardPrivacySkipReason;
}

export async function clipboardPrivacyClassify(
  sourceBundleId: string | null,
): Promise<ClipboardPrivacyClassification | null> {
  return invokeSafe<ClipboardPrivacyClassification>('clipboard_privacy_classify', {
    sourceBundleId,
  });
}

export async function clipboardPrivacyGetSessionStats(): Promise<Record<string, number> | null> {
  return invokeSafe<Record<string, number>>('clipboard_privacy_get_session_stats');
}

export async function clipboardPrivacySetUserDenylist(entries: string[]): Promise<void | null> {
  return invokeSafe<void>('clipboard_privacy_set_user_denylist', { entries });
}

export async function clipboardPrivacyGetUserDenylist(): Promise<string[] | null> {
  return invokeSafe<string[]>('clipboard_privacy_get_user_denylist');
}

export async function clipboardPrivacyGetDefaultDenylist(): Promise<string[] | null> {
  return invokeSafe<string[]>('clipboard_privacy_get_default_denylist');
}

// ── Secret Detection (pattern-based redaction) ────────────────────────────────

export interface SecretRedactionResult {
  content: string;
  kinds: string[];
  oversizedUnscanned: boolean;
}

export interface SecretDetectorRule {
  kind: string;
  description: string;
}

export async function secretDetectionRedact(input: string): Promise<SecretRedactionResult | null> {
  return invokeSafe<SecretRedactionResult>('secret_detection_redact', { input });
}

export async function secretDetectionGetSessionStats(): Promise<Record<string, number> | null> {
  return invokeSafe<Record<string, number>>('secret_detection_get_session_stats');
}

export async function secretDetectionGetCatalog(): Promise<SecretDetectorRule[] | null> {
  return invokeSafe<SecretDetectorRule[]>('secret_detection_get_catalog');
}

// ── At-rest encryption ────────────────────────────────────────────────────────

export interface EncryptionStatusPayload {
  status: 'active' | 'fallback';
  isOsBacked: boolean;
}

export async function cryptoGetStatus(): Promise<EncryptionStatusPayload | null> {
  return invokeSafe<EncryptionStatusPayload>('crypto_get_status');
}

export async function cryptoEncrypt(plaintext: string): Promise<string | null> {
  return invokeSafe<string>('crypto_encrypt', { plaintext });
}

export async function cryptoDecrypt(value: string): Promise<string | null> {
  return invokeSafe<string>('crypto_decrypt', { value });
}
