packages:
  - 'asyar-launcher'
  - 'asyar-sdk'
  - 'extensions/*'
  - 'asyar-launcher/src/extensions/*'

allowBuilds:
  esbuild: true
  keytar: true

onlyBuiltDependencies:
  - 'esbuild'
  - 'keytar'

supportedArchitectures:
  cpu:
    - 'arm64'
    - 'x64'
  os:
    - 'win32'
    - 'darwin'
    - 'linux'

overrides:
  vite: '6.4.3'
  asyar-sdk: 'workspace:*'
