use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Mutex;

#[cfg(target_os = "linux")]
pub mod linux;
#[cfg(target_os = "macos")]
pub mod macos;
#[cfg(target_os = "windows")]
pub mod windows;

/// Platform dispatcher — reads the current pasteboard's type identifiers.
/// Linux and unsupported platforms always return empty.
pub fn read_current_pasteboard_types() -> Vec<String> {
    #[cfg(target_os = "macos")]
    let result = macos::read_pasteboard_types();
    #[cfg(target_os = "windows")]
    let result = windows::read_pasteboard_types();
    #[cfg(target_os = "linux")]
    let result = linux::read_pasteboard_types();
    #[cfg(not(any(target_os = "macos", target_os = "windows", target_os = "linux")))]
    let result: Vec<String> = Vec::new();
    result
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", tag = "kind", content = "value")]
pub enum SkipReason {
    None,
    Transient,
    Concealed,
    AutoGenerated,
    OptedOutOfHistory,
    SourceDenylist(String),
}

pub const DEFAULT_DENYLIST_MACOS: &[&str] = &[
    "com.agilebits.onepassword7",
    "com.1password.1password",
    "com.bitwarden.desktop",
    "org.keepassxc.KeePassXC",
    "com.dashlane.dashlanephonefinal",
    "io.enpass.mac",
    "com.apple.keychainaccess",
    "com.lastpass.LastPass",
];

pub const DEFAULT_DENYLIST_WINDOWS: &[&str] = &[
    "1Password.exe",
    "Bitwarden.exe",
    "KeePassXC.exe",
    "KeePass.exe",
    "Dashlane.exe",
    "Enpass.exe",
    "LastPass.exe",
];

pub const DEFAULT_DENYLIST_LINUX: &[&str] = &[
    "1password.desktop",
    "bitwarden.desktop",
    "org.keepassxc.KeePassXC.desktop",
    "com.dashlane.Dashlane.desktop",
    "io.enpass.Enpass.desktop",
];

pub fn default_denylist() -> Vec<String> {
    #[cfg(target_os = "macos")]
    let list = DEFAULT_DENYLIST_MACOS;
    #[cfg(target_os = "windows")]
    let list = DEFAULT_DENYLIST_WINDOWS;
    #[cfg(target_os = "linux")]
    let list = DEFAULT_DENYLIST_LINUX;
    #[cfg(not(any(target_os = "macos", target_os = "windows", target_os = "linux")))]
    let list: &[&str] = &[];
    list.iter().map(|s| s.to_string()).collect()
}

pub fn merged_denylist(user: &[String]) -> Vec<String> {
    let mut out = default_denylist();
    for entry in user {
        if !out.iter().any(|d| d.eq_ignore_ascii_case(entry)) {
            out.push(entry.clone());
        }
    }
    out
}

/// Classify a clipboard event as syncable / excluded.
///
/// Pasteboard-flag inspection takes priority over the source-app denylist —
/// a flag is the source app's explicit "do not capture" signal, while a
/// denylist hit is a coarser policy default.
pub fn classify(
    pasteboard_types: &[String],
    source_bundle_id: Option<&str>,
    user_denylist: &[String],
) -> SkipReason {
    for t in pasteboard_types {
        if t.eq_ignore_ascii_case("org.nspasteboard.ConcealedType") {
            return SkipReason::Concealed;
        }
        if t.eq_ignore_ascii_case("org.nspasteboard.TransientType") {
            return SkipReason::Transient;
        }
        if t.eq_ignore_ascii_case("org.nspasteboard.AutoGeneratedType")
            || t.eq_ignore_ascii_case(
                "com.apple.pasteboard.promised-type-NSStringPboardTypeAutoGenerated",
            )
        {
            return SkipReason::AutoGenerated;
        }
        if t.eq_ignore_ascii_case("CanIncludeInClipboardHistory")
            || t.eq_ignore_ascii_case("ExcludeClipboardContentFromMonitorProcessing")
        {
            return SkipReason::OptedOutOfHistory;
        }
    }

    if let Some(bundle) = source_bundle_id {
        let merged = merged_denylist(user_denylist);
        if merged.iter().any(|d| d.eq_ignore_ascii_case(bundle)) {
            return SkipReason::SourceDenylist(bundle.to_string());
        }
    }

    SkipReason::None
}

pub struct ClipboardPrivacyState {
    session_skips: Mutex<HashMap<String, u32>>,
}

impl ClipboardPrivacyState {
    pub fn new() -> Self {
        Self {
            session_skips: Mutex::new(HashMap::new()),
        }
    }

    pub fn record_skip(&self, reason: &SkipReason) {
        let key = match reason {
            SkipReason::None => return,
            SkipReason::Transient => "transient".to_string(),
            SkipReason::Concealed => "concealed".to_string(),
            SkipReason::AutoGenerated => "auto_generated".to_string(),
            SkipReason::OptedOutOfHistory => "opted_out_of_history".to_string(),
            SkipReason::SourceDenylist(b) => format!("source_denylist:{b}"),
        };
        if let Ok(mut map) = self.session_skips.lock() {
            *map.entry(key).or_insert(0) += 1;
        }
    }

    pub fn get_session_stats(&self) -> HashMap<String, u32> {
        self.session_skips
            .lock()
            .map(|m| m.clone())
            .unwrap_or_default()
    }
}

impl Default for ClipboardPrivacyState {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn s(v: &str) -> String {
        v.to_string()
    }

    #[test]
    fn classify_returns_none_when_no_flags_or_denylist_match() {
        let result = classify(
            &[s("public.utf8-plain-text")],
            Some("com.apple.TextEdit"),
            &[],
        );
        assert_eq!(result, SkipReason::None);
    }

    #[test]
    fn classify_skips_transient_pasteboard_type() {
        let result = classify(
            &[
                s("public.utf8-plain-text"),
                s("org.nspasteboard.TransientType"),
            ],
            None,
            &[],
        );
        assert_eq!(result, SkipReason::Transient);
    }

    #[test]
    fn classify_skips_concealed_pasteboard_type() {
        let result = classify(&[s("org.nspasteboard.ConcealedType")], None, &[]);
        assert_eq!(result, SkipReason::Concealed);
    }

    #[test]
    fn classify_skips_nspasteboard_auto_generated_type() {
        let result = classify(&[s("org.nspasteboard.AutoGeneratedType")], None, &[]);
        assert_eq!(result, SkipReason::AutoGenerated);
    }

    #[test]
    fn classify_skips_apple_auto_generated_type() {
        let result = classify(
            &[s(
                "com.apple.pasteboard.promised-type-NSStringPboardTypeAutoGenerated",
            )],
            None,
            &[],
        );
        assert_eq!(result, SkipReason::AutoGenerated);
    }

    #[test]
    fn classify_skips_windows_can_include_in_history_zero() {
        let result = classify(&[s("CanIncludeInClipboardHistory")], None, &[]);
        assert_eq!(result, SkipReason::OptedOutOfHistory);
    }

    #[test]
    fn classify_skips_windows_exclude_from_monitor_processing() {
        let result = classify(
            &[s("ExcludeClipboardContentFromMonitorProcessing")],
            None,
            &[],
        );
        assert_eq!(result, SkipReason::OptedOutOfHistory);
    }

    #[test]
    fn classify_skips_when_source_in_user_denylist() {
        let result = classify(
            &[s("public.utf8-plain-text")],
            Some("com.example.MyVault"),
            &[s("com.example.MyVault")],
        );
        assert_eq!(
            result,
            SkipReason::SourceDenylist("com.example.MyVault".into())
        );
    }

    #[test]
    fn classify_is_case_insensitive_on_bundle_match() {
        let result = classify(
            &[s("public.utf8-plain-text")],
            Some("COM.EXAMPLE.MYVAULT"),
            &[s("com.example.myvault")],
        );
        assert_eq!(
            result,
            SkipReason::SourceDenylist("COM.EXAMPLE.MYVAULT".into())
        );
    }

    #[test]
    fn classify_no_source_app_does_not_match_denylist() {
        let result = classify(
            &[s("public.utf8-plain-text")],
            None,
            &[s("com.example.MyVault")],
        );
        assert_eq!(result, SkipReason::None);
    }

    #[test]
    fn classify_pasteboard_flag_takes_priority_over_denylist() {
        let result = classify(
            &[s("org.nspasteboard.ConcealedType")],
            Some("com.example.MyVault"),
            &[s("com.example.MyVault")],
        );
        assert_eq!(result, SkipReason::Concealed);
    }

    #[test]
    fn merged_denylist_dedupes_user_additions() {
        // On macOS the default list includes com.bitwarden.desktop;
        // a user re-adding it must dedupe. On other platforms the default
        // list differs, so we use a known-default entry for this platform.
        #[cfg(target_os = "macos")]
        let known_default = "com.bitwarden.desktop".to_string();
        #[cfg(target_os = "windows")]
        let known_default = "Bitwarden.exe".to_string();
        #[cfg(target_os = "linux")]
        let known_default = "bitwarden.desktop".to_string();
        #[cfg(not(any(target_os = "macos", target_os = "windows", target_os = "linux")))]
        let known_default = "_unused".to_string();

        let user = vec![known_default.clone(), "com.example.MyVault".to_string()];
        let merged = merged_denylist(&user);
        let count = merged
            .iter()
            .filter(|d| d.eq_ignore_ascii_case(&known_default))
            .count();

        #[cfg(any(target_os = "macos", target_os = "windows", target_os = "linux"))]
        assert_eq!(count, 1, "default + duplicate user entry should dedupe");

        assert!(merged.iter().any(|d| d == "com.example.MyVault"));
        let _ = count;
    }

    #[test]
    fn state_starts_with_zero_counts() {
        let state = ClipboardPrivacyState::new();
        let stats = state.get_session_stats();
        assert!(stats.is_empty() || stats.values().all(|v| *v == 0));
    }

    #[test]
    fn state_increments_counter_on_skip() {
        let state = ClipboardPrivacyState::new();
        state.record_skip(&SkipReason::Transient);
        state.record_skip(&SkipReason::Transient);
        state.record_skip(&SkipReason::Concealed);
        let stats = state.get_session_stats();
        assert_eq!(stats.get("transient").copied().unwrap_or(0), 2);
        assert_eq!(stats.get("concealed").copied().unwrap_or(0), 1);
    }

    #[test]
    fn state_does_not_record_skip_for_none() {
        let state = ClipboardPrivacyState::new();
        state.record_skip(&SkipReason::None);
        let stats = state.get_session_stats();
        assert!(stats.is_empty() || stats.values().all(|v| *v == 0));
    }

    #[test]
    fn state_records_source_denylist_with_bundle_id() {
        let state = ClipboardPrivacyState::new();
        state.record_skip(&SkipReason::SourceDenylist("com.bitwarden.desktop".into()));
        let stats = state.get_session_stats();
        assert_eq!(
            stats
                .get("source_denylist:com.bitwarden.desktop")
                .copied()
                .unwrap_or(0),
            1
        );
    }
}
