// AUTO-GENERATED by scripts/generate-permission-catalog.mjs — do not edit.
// Run `pnpm gen:permission-catalog` after changing
// permissions.rs::get_required_permission.

// Every permission string that Rust's get_required_permission can require —
// i.e. gates at least one asyar:api:* call. Not the full set of manifest-
// declarable permissions (see asyar-sdk/cli/lib/manifest.ts VALID_PERMISSIONS
// for that); some permissions are declarative-only and never appear here.
export const GATED_PERMISSIONS = [
  "app:frontmost-watch",
  "application:read",
  "browser:bookmarks.read",
  "browser:history.read",
  "browser:page.read",
  "browser:page.write",
  "browser:tabs.read",
  "browser:tabs.write",
  "cache:read",
  "cache:write",
  "clipboard:read",
  "clipboard:write",
  "entitlements:read",
  "extension:invoke",
  "feedback:announce",
  "files:read",
  "files:search",
  "fs:read",
  "fs:watch",
  "fs:write",
  "network",
  "notes:read",
  "notes:write",
  "notifications:send",
  "oauth:use",
  "power:inhibit",
  "preferences:read",
  "preferences:write",
  "process:kill",
  "process:read",
  "runs:track",
  "screen:pick-color",
  "selection:read",
  "shell:open-url",
  "shell:spawn",
  "snippets:contribute",
  "storage:read",
  "storage:write",
  "systemEvents:read",
  "timers:cancel",
  "timers:list",
  "timers:schedule",
  "tools:register",
  "window:manage"
] as const;
